
name: Deploy to CapRover

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase Repo Name
        run: echo "IMAGE_REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # BACKEND
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Sapienza.Dominus.HttpApi.Host/Dockerfile
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPO }}/backend:latest

      - name: Deploy Backend to CapRover
        run: |
          npm install -g caprover
          caprover deploy -h '${{ secrets.CAPROVER_SERVER }}' -p '${{ secrets.CAPROVER_PASSWORD }}' -a '${{ secrets.CAPROVER_APP_BACKEND }}' -i 'ghcr.io/${{ env.IMAGE_REPO }}/backend:latest'

      # FRONTEND
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./abp-react-v2
          file: ./abp-react-v2/Dockerfile
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPO }}/frontend:latest

      - name: Deploy Frontend to CapRover
        run: |
          caprover deploy -h '${{ secrets.CAPROVER_SERVER }}' -p '${{ secrets.CAPROVER_PASSWORD }}' -a '${{ secrets.CAPROVER_APP_FRONTEND }}' -i 'ghcr.io/${{ env.IMAGE_REPO }}/frontend:latest'
